name: Update RSS Feed

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Set Up Google Cloud Credentials
        run: |
          echo "${{ secrets.BIGQUERY_CREDENTIALS }}" | base64 --decode > credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json" >> $GITHUB_ENV
        shell: bash

      - name: Set Up Environment Variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: Run Script
        run: python main.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed.xml public/img
          git commit -m "Update RSS feed and images" || echo "No changes to commit"
          git push
